//! Centralised input validators for filesystem-bound identifiers.
//!
//! Audit F62 + "Suggested path validation helpers" (2026-05-11): every
//! filesystem write or `docker cp` whose name comes from an HTTP body or
//! header MUST run through one of these validators first. Anything outside
//! the strict character set is rejected before the value is joined into a
//! `PathBuf`, so path-traversal (`../`), absolute paths, NUL bytes,
//! Windows separators, URL-encoded separators, and pathological lengths
//! are all impossible to construct.
//!
//! The validators intentionally avoid the `regex` crate (matches the
//! existing convention in `replication.rs`, which already hand-rolls a
//! WAL-name validator) to keep the dependency surface small.

use std::path::{Component, Path, PathBuf};

/// Instance IDs are generated by `nanoid`-style alphabets. Real values are
/// 12-24 chars of `[A-Za-z0-9_-]`. Bound is loose enough to accept future
/// variations and tight enough to reject anything path-like.
pub fn validate_instance_id_component(s: &str) -> Result<(), String> {
    if s.is_empty() {
        return Err("instance_id is empty".into());
    }
    if s.len() > 64 {
        return Err(format!("instance_id too long (max 64, got {})", s.len()));
    }
    for c in s.chars() {
        let ok = c.is_ascii_alphanumeric() || c == '_' || c == '-';
        if !ok {
            return Err(format!("instance_id contains invalid character {c:?}"));
        }
    }
    Ok(())
}

/// WAL segment names produced by Postgres. Accepted forms:
///   * 24 hex chars (uppercase): `000000010000000000000001`
///   * 24 hex chars + `.partial`: `000000010000000000000001.partial`
///   * 8 hex chars + `.history`: `00000002.history`
///
/// This mirrors the validator already inlined in `process_instance_wal`,
/// but is callable from the receive side where the name is attacker-
/// controlled via the X-Segment-Name header.
pub fn validate_segment_name(s: &str) -> Result<(), String> {
    if s.is_empty() {
        return Err("segment_name is empty".into());
    }
    if s.len() < 9 || s.len() > 32 {
        return Err(format!(
            "segment_name length {} outside Postgres WAL bounds (9..=32)",
            s.len()
        ));
    }
    fn is_upper_hex(c: char) -> bool {
        c.is_ascii_digit() || (c.is_ascii_alphabetic() && c.is_ascii_uppercase() && c.is_ascii_hexdigit())
    }
    let (head, tail) = s.split_at(8);
    if !head.chars().all(is_upper_hex) {
        return Err("segment_name: leading 8 chars must be uppercase hex".into());
    }
    if tail == ".history" {
        return Ok(());
    }
    let (mid, ext) = if let Some(stripped) = tail.strip_suffix(".partial") {
        (stripped, ".partial")
    } else {
        (tail, "")
    };
    if mid.len() != 16 {
        return Err("segment_name: middle must be 16 hex chars (24-char WAL name)".into());
    }
    if !mid.chars().all(is_upper_hex) {
        return Err("segment_name: middle 16 chars must be uppercase hex".into());
    }
    if !ext.is_empty() && ext != ".partial" {
        return Err(format!("segment_name: unexpected suffix {ext:?}"));
    }
    Ok(())
}

/// Function names accepted by the Edge Functions deploy path. Matches the
/// kraph_deploy_function regex on the gateway: lowercase alphanumeric and
/// hyphens, 1..=64 chars.
pub fn validate_function_name(s: &str) -> Result<(), String> {
    if s.is_empty() {
        return Err("function_name is empty".into());
    }
    if s.len() > 64 {
        return Err(format!("function_name too long (max 64, got {})", s.len()));
    }
    for c in s.chars() {
        let ok = c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-';
        if !ok {
            return Err(format!("function_name contains invalid character {c:?}"));
        }
    }
    Ok(())
}

/// Env-var key validator. `[A-Za-z_][A-Za-z0-9_]*`, 1..=128 chars.
/// Mirrors `main::validate_env_key`; kept here so all path-bound input
/// validators live in one module.
pub fn validate_env_key(s: &str) -> Result<(), String> {
    if s.is_empty() {
        return Err("env_key is empty".into());
    }
    if s.len() > 128 {
        return Err("env_key exceeds 128 chars".into());
    }
    let mut chars = s.chars();
    let first = chars.next().unwrap();
    if !(first.is_ascii_alphabetic() || first == '_') {
        return Err("env_key must start with a letter or underscore".into());
    }
    for c in chars {
        if !(c.is_ascii_alphanumeric() || c == '_') {
            return Err(format!("env_key contains invalid character {c:?}"));
        }
    }
    Ok(())
}

/// Join `components` under `base` and assert the result is still under
/// `base` after canonicalisation. Refuses if any component contains a
/// path separator, is `.` / `..`, is absolute, or contains a NUL byte.
///
/// Use this for any filesystem write whose final path is derived from
/// HTTP-supplied identifiers. It defends against:
///   * `../` traversal
///   * absolute paths (`/etc/passwd`, `C:\Windows`)
///   * Windows separators on Linux nodes
///   * symlink-in-base shenanigans (canonicalises `base` and compares
///     prefixes on the resolved path)
pub fn safe_join_under(base: &Path, components: &[&str]) -> Result<PathBuf, String> {
    for c in components {
        if c.is_empty() {
            return Err("path component is empty".into());
        }
        if c.contains('\0') {
            return Err("path component contains NUL byte".into());
        }
        if c.contains('/') || c.contains('\\') {
            return Err(format!("path component {c:?} contains a separator"));
        }
        if *c == "." || *c == ".." {
            return Err(format!("path component {c:?} is a special directory"));
        }
        if Path::new(c)
            .components()
            .any(|comp| !matches!(comp, Component::Normal(_)))
        {
            return Err(format!("path component {c:?} is not a normal path part"));
        }
    }

    let mut joined = base.to_path_buf();
    for c in components {
        joined.push(c);
    }

    // The lexical join is already safe because every `c` is a Normal
    // path component — `joined` is literally `base + N normal segments`
    // with no traversal. The canonicalise step below is the defence
    // against `base` itself being (or containing) a symlink to
    // somewhere unexpected. We walk up from `joined` to find the
    // deepest existing ancestor and canonicalise THAT, so we can
    // compare on the same platform-normalised form (Windows
    // canonicalize prefixes `\\?\`, comparing canonical-vs-literal
    // would always fail).
    if base.exists() {
        let base_real = base
            .canonicalize()
            .map_err(|e| format!("canonicalize base: {e}"))?;
        let mut probe: &std::path::Path = joined.as_path();
        let ancestor_real = loop {
            if probe.exists() {
                break probe
                    .canonicalize()
                    .map_err(|e| format!("canonicalize ancestor: {e}"))?;
            }
            match probe.parent() {
                Some(p) => probe = p,
                None => break std::path::PathBuf::new(),
            }
        };
        // Empty ancestor means base itself doesn't show up on the walk
        // — that's a bug in our logic since we already verified base
        // exists at the top of this `if`. Treat it as a containment
        // failure so we err on the side of refusing rather than
        // silently allowing.
        if ancestor_real.as_os_str().is_empty()
            || !ancestor_real.starts_with(&base_real)
        {
            return Err(format!(
                "joined path {ancestor_real:?} escapes base {base_real:?}"
            ));
        }
    }
    Ok(joined)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn instance_id_rejects_traversal() {
        assert!(validate_instance_id_component("..").is_err());
        assert!(validate_instance_id_component("../etc/passwd").is_err());
        assert!(validate_instance_id_component("a/b").is_err());
        assert!(validate_instance_id_component("a\\b").is_err());
        assert!(validate_instance_id_component("a\0b").is_err());
        assert!(validate_instance_id_component("").is_err());
        assert!(validate_instance_id_component(&"a".repeat(65)).is_err());
        assert!(validate_instance_id_component("inst_01_abcDEF-09").is_ok());
    }

    #[test]
    fn segment_name_accepts_postgres_forms_only() {
        assert!(validate_segment_name("000000010000000000000001").is_ok());
        assert!(validate_segment_name("000000010000000000000001.partial").is_ok());
        assert!(validate_segment_name("00000002.history").is_ok());
        // Lowercase hex rejected (Postgres uses uppercase).
        assert!(validate_segment_name("00000001000000000000000a").is_err());
        // Path-traversal attempts.
        assert!(validate_segment_name("../etc/passwd").is_err());
        assert!(validate_segment_name("00000001/0000000000000001").is_err());
        // Wrong length.
        assert!(validate_segment_name("0000").is_err());
        assert!(validate_segment_name(&"A".repeat(33)).is_err());
    }

    #[test]
    fn function_name_rejects_path_chars() {
        assert!(validate_function_name("process-webhook").is_ok());
        assert!(validate_function_name("WEBHOOK").is_err()); // uppercase
        assert!(validate_function_name("foo/bar").is_err());
        assert!(validate_function_name("..").is_err());
        assert!(validate_function_name("").is_err());
    }

    #[test]
    fn env_key_matches_compose() {
        assert!(validate_env_key("OPENAI_API_KEY").is_ok());
        assert!(validate_env_key("_PRIVATE").is_ok());
        assert!(validate_env_key("1BAD").is_err());
        assert!(validate_env_key("HAS-DASH").is_err());
        assert!(validate_env_key("").is_err());
    }

    #[test]
    fn safe_join_rejects_traversal_components() {
        let tmp = std::env::temp_dir().join("kraph-path-safety-test");
        let _ = std::fs::create_dir_all(&tmp);
        assert!(safe_join_under(&tmp, &["foo", "bar"]).is_ok());
        assert!(safe_join_under(&tmp, &[".."]).is_err());
        assert!(safe_join_under(&tmp, &["..", "etc"]).is_err());
        assert!(safe_join_under(&tmp, &["a/b"]).is_err());
        assert!(safe_join_under(&tmp, &["a\\b"]).is_err());
        assert!(safe_join_under(&tmp, &["a\0b"]).is_err());
        assert!(safe_join_under(&tmp, &[""]).is_err());
        assert!(safe_join_under(&tmp, &["."]).is_err());
        // URL-encoded sep is just text, so it's accepted as a single
        // component. The receive handler decodes URL-encoding BEFORE
        // calling the validator, so this is fine.
        assert!(safe_join_under(&tmp, &["a%2Fb"]).is_ok());
    }
}
